[project]
name = "trader-kis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "pydantic-settings>=2.7.1",
    "pytest>=8.3.4",
    "python-kis==2.1.3",
    "ruff>=0.9.1",
    "tzdata>=2025.1",
]
