"""change pk to stock_code

Revision ID: 13caa98c019e
Revises: df6443b1f661
Create Date: 2025-08-10 17:34:41.378316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "13caa98c019e"
down_revision: Union[str, Sequence[str], None] = "df6443b1f661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidate_stock",
        "stock_code",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=6),
        nullable=False,
    )
    op.drop_column("candidate_stock", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("candidate_stock", sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column(
        "candidate_stock",
        "stock_code",
        existing_type=mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=6),
        nullable=True,
    )
    # ### end Alembic commands ###
