"""Create initial tables

Revision ID: 7dd1380f5310
Revises:
Create Date: 2025-08-10 16:45:22.709846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7dd1380f5310"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_stock",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("corp_code", sa.String(length=8), nullable=True),
        sa.Column("corp_name", sa.String(length=150), nullable=True),
        sa.Column("stock_code", sa.String(length=6), nullable=True),
        sa.Column("financial_stability_score", sa.Integer(), nullable=True),
        sa.Column("growth_score", sa.Integer(), nullable=True),
        sa.Column("valuation_attractiveness", sa.Integer(), nullable=True),
        sa.Column("support_price", sa.Integer(), nullable=True),
        sa.Column("resistance_price", sa.Integer(), nullable=True),
        sa.Column("technical_signal", sa.String(length=30), nullable=True),
        sa.Column("date", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidate_stock")
    # ### end Alembic commands ###
