"""Change valudation_attractiveness

Revision ID: df6443b1f661
Revises: 7dd1380f5310
Create Date: 2025-08-10 17:27:47.063110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "df6443b1f661"
down_revision: Union[str, Sequence[str], None] = "7dd1380f5310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidate_stock",
        "valuation_attractiveness",
        existing_type=mysql.INTEGER(),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidate_stock",
        "valuation_attractiveness",
        existing_type=sa.String(length=30),
        type_=mysql.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
