"""Create initial tables

Revision ID: 61daf192a24b
Revises:
Create Date: 2025-08-08 18:32:11.543223

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "61daf192a24b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
