"""Create initial tables

Revision ID: 2d4460acacf2
Revises:
Create Date: 2025-08-10 16:45:31.760806

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2d4460acacf2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_info",
        sa.Column("corp_code", sa.String(length=8), nullable=False),
        sa.Column("corp_name", sa.String(length=150), nullable=True),
        sa.Column("corp_eng_name", sa.String(length=150), nullable=True),
        sa.Column("stock_code", sa.String(length=6), nullable=True),
        sa.Column("modify_date", sa.String(length=8), nullable=True),
        sa.PrimaryKeyConstraint("corp_code"),
    )
    op.create_table(
        "corporate_quote",
        sa.Column("symbol", sa.String(length=6), nullable=False),
        sa.Column("market", sa.String(length=10), nullable=True),
        sa.Column("sector_name", sa.String(length=30), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("amount", sa.BigInteger(), nullable=True),
        sa.Column("market_cap", sa.BigInteger(), nullable=True),
        sa.Column("sign", sa.String(length=10), nullable=True),
        sa.Column("sign_name", sa.String(length=20), nullable=True),
        sa.Column("risk", sa.String(length=50), nullable=True),
        sa.Column("halt", sa.Boolean(), nullable=True),
        sa.Column("overbought", sa.String(length=50), nullable=True),
        sa.Column("prev_price", sa.Float(), nullable=True),
        sa.Column("prev_volume", sa.BigInteger(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("rate", sa.Float(), nullable=True),
        sa.Column("high_limit", sa.Float(), nullable=True),
        sa.Column("low_limit", sa.Float(), nullable=True),
        sa.Column("unit", sa.Integer(), nullable=True),
        sa.Column("tick", sa.Float(), nullable=True),
        sa.Column("decimal_places", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("exchange_rate", sa.Float(), nullable=True),
        sa.Column("open_price", sa.Float(), nullable=True),
        sa.Column("high_price", sa.Float(), nullable=True),
        sa.Column("low_price", sa.Float(), nullable=True),
        sa.Column("eps", sa.Float(), nullable=True),
        sa.Column("bps", sa.Float(), nullable=True),
        sa.Column("per", sa.Float(), nullable=True),
        sa.Column("pbr", sa.Float(), nullable=True),
        sa.Column("week52_high", sa.Float(), nullable=True),
        sa.Column("week52_low", sa.Float(), nullable=True),
        sa.Column("week52_high_date", sa.Date(), nullable=True),
        sa.Column("week52_low_date", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("symbol"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("corporate_quote")
    op.drop_table("corporate_info")
    # ### end Alembic commands ###
